dbt_intermediate_project:
  target: dev
  
  outputs:
    dev:
      type: snowflake
      account: YOUR_ACCOUNT
      user: YOUR_USER
      role: ACCOUNTADMIN
      database: DBT_HANDSON
      warehouse: COMPUTE_WH
      schema: ANALYTICS
      threads: 4
